site_name: netcorepal-cloud-framework
site_description: A tactical framework for Domain-Driven Design based on ASP.NET Core.
site_author: NetCorePal #作者名
site_url: https://netcorepal.github.io/netcorepal-cloud-framework  #网站地址
copyright: Copyright &copy; 2024 NetCorePal # 左下角的版权声明

repo_name: "GitHub"
repo_url: "https://github.com/netcorepal/netcorepal-cloud-framework"
edit_uri: "edit/master/docs/content"
docs_dir: "content"

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.instant

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: true
      linenums: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: netcorepal
      repo: netcorepal-cloud-framework
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - 首页: index.md
  - 中文文档:
    - 入门: 
      - 创建项目: zh/getting-started/getting-started.md
      - 项目结构: zh/getting-started/project-structure.md
      - 开发流程: zh/getting-started/development-process.md 
      - DDD原则: zh/rules-of-ddd/rules-of-ddd.md
    - 关于AI: zh/about-ai.md
    - 领域层:
      - 强类型ID: zh/domain/strong-typed-id.md
      - 领域模型: zh/domain/domain-entity.md
      - 领域事件: zh/domain/domain-event.md
      - 更新时间: zh/domain/update-time.md
      - 软删除: zh/domain/soft-delete.md
      # - 值对象: zh/domain/domain-value-object.md
    #- ID生成器:
      #- Snowflake: zh/id-generator/snowflake.md
      #- Etcd: zh/id-generator/etcd-worker-id-generator.md
    - 数据访问:
      - ID生成: zh/data/id-generator.md
      - 仓储: zh/data/repository.md
      - UnitOfWork: zh/data/unit-of-work.md
    - 事务处理: zh/transactions/transactions.md
    - 事件处理:
      - 领域事件处理器: zh/events/domain-event-handler.md
      - 集成事件处理器: zh/events/integration-event-handler.md
      - 集成事件转换器: zh/events/integration-converter.md
    - 服务发现: zh/service-discovery/service-discovery.md
    - 上下文传递: 
      - 上下文: zh/context/context.md
      - 如何自定义上下文类型: zh/context/custom-context-type.md
    - 并发控制:
      - 乐观锁-行版本号: zh/concurrency/row-version.md
      - 悲观锁-Redis锁: zh/concurrency/redis-lock.md
      - 命令锁: zh/concurrency/command-lock.md
    - 多环境: zh/env/multi-env.md
    - AspNetCore扩展:
      - 异常处理: zh/aspnetcore/exception-handling.md
      - 数据响应: zh/aspnetcore/response-data.md
      - Json序列化: zh/aspnetcore/json.md
      - Jwt认证: zh/aspnetcore/jwt.md
      - 时区处理: zh/aspnetcore/time-zone.md
    - 分库分表:
      - 分库分表介绍: zh/sharding/data-sharding.md
      - 读写分离: zh/sharding/read-write-separation.md
      - 分表: zh/sharding/sharding-table.md
      - 分库: zh/sharding/sharding-database.md
      - 多租户分库: zh/sharding/sharding-tenant.md
  - English Docs:
    - Home: en/index.md
    - Getting Started:
        - Create Project: en/getting-started/getting-started.md
        - Project Structure: en/getting-started/project-structure.md
        - Development Process: en/getting-started/development-process.md
    - DDD Principles: en/rules-of-ddd/rules-of-ddd.md
    - About AI: en/about-ai.md
    - Domain Layer:
        - Strongly Typed ID: en/domain/strong-typed-id.md
        - Domain Model: en/domain/domain-entity.md
        - Domain Event: en/domain/domain-event.md
        - Update Time: en/domain/update-time.md
        - Soft Delete: en/domain/soft-delete.md
      # - Value Object: domain/domain-value-object.md
    #- ID Generator:
        #- Snowflake: en/id-generator/snowflake.md
        #- Etcd: en/id-generator/etcd-worker-id-generator.md
    - Data Access:
        - ID Generator: en/data/id-generator.md
        - Repository: en/data/repository.md
        - UnitOfWork: en/data/unit-of-work.md
    - Transaction Handling: en/transactions/transactions.md
    - Event Handling:
        - Domain Event Handler: en/events/domain-event-handler.md
        - Integration Event Handler: en/events/integration-event-handler.md
        - Integration Converter: en/events/integration-converter.md
    - Service Discovery: en/service-discovery/service-discovery.md
    - Context Passing:
        - Context: en/context/context.md
        - How to Customize Context Type: en/context/custom-context-type.md
    - Concurrency Control:
        - Optimistic Lock - Row Version: en/concurrency/row-version.md
        - Pessimistic Lock - Redis Lock: en/concurrency/redis-lock.md
        - Command Lock: en/concurrency/command-lock.md
    - Multi-Environment: en/env/multi-env.md
    - AspNetCore Extensions:
        - Exception Handling: en/aspnetcore/exception-handling.md
        - Data Response: en/aspnetcore/response-data.md
        - Json Serialization: en/aspnetcore/json.md
        - Jwt Authentication: en/aspnetcore/jwt.md
        - Time Zone Handling: en/aspnetcore/time-zone.md
    - Sharding and Partitioning:
        - Introduction to Sharding and Partitioning: en/sharding/data-sharding.md
        - Read-Write Separation: en/sharding/read-write-separation.md
        - Table Partitioning: en/sharding/sharding-table.md
        - Database Partitioning: en/sharding/sharding-database.md
        - Multi-Tenant Database Partitioning: en/sharding/sharding-tenant.md
